### ISSUE TITLE
Unresponsive motor after unknown reasons

### ISSUE THREAD

**Issue by Trilis29** [Gifford47/HCPBridgeMqtt#37] opened 2023-08-17 10:00 UTC
**Describe the bug**
It is not the first time that motor gets unresponsive and I see not connected on web interface. After the night woke up tried to open door and it is not opening. And it is impossible to open the door with push button, remote butoon, nothing works. I have restarted bus search with last dip switch it got connected again and it is working. 

**To Reproduce**
1. Which motor do you have? Promatic 4
2. Which branch/release did you use? Gifford47
3. Which peripherals (bme280, HCsr04, ...) did you use? no

**Expected behavior**
It should reconnect or disconnect and do not disturb the gates to be opened with button without restarting.

**Comment by Gifford47** [comment] 2023-08-17 10:05
Did you use development or master branch?

Did you notice a WiFi reconnect in that time?

**Comment by 14yannick** [comment] 2023-08-17 10:06
Hi @Trilis29,

Do you motor show an error code (Promatic blink Red). If yes how many time.

Did you have the error with a build with the code of the Actual master Branch?

**Comment by Trilis29** [comment] 2023-08-17 10:45
> Did you use development or master branch?
> 
> Did you notice a WiFi reconnect in that time?

If I recall correctly it was development branch.



> Hi @Trilis29,
> 
> Do you motor show an error code (Promatic blink Red). If yes how many time.
> 
> Did you have the error with a build with the code of the Actual master Branch?

I had this error with your build, also will try to flash now master and will see if it happens again. But this is not the first time

**Comment by 14yannick** [comment] 2023-08-17 11:08
If you face again this error. Please tell if your motor blinks red when it's unresponsive.

**Comment by i5Js** [comment] 2023-08-26 16:51
I having this issue to, same door. I see an error code 07 in the display. It happens, usually, when I open the door using the remote control. 

Thanks for your job

**Comment by 14yannick** [comment] 2023-08-26 17:34
@i5Js which build are you using. Are you using the current master?

**Comment by i5Js** [comment] 2023-08-26 17:48
@14yannick Indeed, the latest one.

**Comment by 14yannick** [comment] 2023-08-26 20:56
Which hardware are you using (chip as precise as possible, pcb, step down, rs485 interface, sensors, ...)
If you have an adjustable step down what is the output voltage.
Are you able to reproduce easily the error with the remote (will help if we have to debug).

**Comment by i5Js** [comment] 2023-08-27 09:52
I'm using this hardware: https://community.home-assistant.io/t/hormann-garage-door-via-mqtt/279938/242 No sensors, just the hardware itself.

I have to remote controls, one at the garage wall, and a hand remote control. It usually happens when I press the button in the wall remote.

**Comment by 14yannick** [comment] 2023-08-27 18:26
That's a good start as I have very similar hardware. is the remote on your wall a Radio sender/receiver or it's a button wired to the motor? For example an it1-b or a regular button wired to terminal 21 and 20 on the motor. 
If you have a multimeter can you check if you have 5v on your 5v pin on the ESP.
Error code 7 is when the esp fails to reply in time to the motors check message. This happen if the ESP reboot.  What we can try is to uncomment [this](https://github.com/Gifford47/HCPBridgeMqtt/blob/cf0b5095b808151ecc573ba843fe82b7980855cf/HCPBridgeESP32/src/configuration.h#L86C1-L88C39) line. This will cause an additional Debug mqtt topic. Try then to recreate the error and check what is the content of the mqtt debug topic.

**Comment by i5Js** [comment] 2023-08-27 19:06
Hey @14yannick Thanks. It’s Radio sender/receiver. There is no wired to the motor. 

I will try to enable the debug and keep this update. 

Thanks!

**Comment by snoekieboe** [comment] 2023-09-01 08:07
I have the exact same issue as described above happen when:

* wifi gets disconnected and reconnected for whatever reason (e.g. poor coverage or Access Point reboot)
* MQTT gets discconnected and reconnected (e.g. whenever i update Home Assistant and it restarts)

**Comment by 14yannick** [comment] 2023-09-01 08:12
@snoekieboe are you running with the current Master Build out of this repo. 
With same issue do you mean that you have an error 7 on the motor as soon wifi or mqtt gets disconnected.

**Comment by snoekieboe** [comment] 2023-09-01 08:14
I'm currrently running the master build out of this repo. I'm not sure i get the error 7 but my symptoms are:

* Web interface says "not connected"
* red light flashing on the motor
* only a power cycle of the motor restores my connectivity/communication

**Comment by 14yannick** [comment] 2023-09-01 08:23
Ok you have a promatic door so I think it flashes 7 times make a short break then flash again 7 times.
When did you build your bin. because the known issue about wifi of mqtt disconnect causing error 7 have been fixed like a month ago in the Master Repo.

**Comment by snoekieboe** [comment] 2023-09-01 08:25
Yes it flashes exactly like that. My currently running build was built on July 10th. Should i build a new one based on master or development to include the fix for this?

**Comment by BradleyFord** [comment] 2023-09-01 08:34
When do we think that the dev branch will move to master and tag as a release? (I am holding back reinstalling until that time)

**Comment by 14yannick** [comment] 2023-09-01 08:48
The fix should already be in the master of the 10th but just around this time we merged my old Repo and have moved around some stuff so please create a new Build out of the master and try again.
@BradleyFord I just have flashed today the development_pref branch where you don't need anymore to setup the variables before the build. The Dev Branch at it is has a small Issue to with the wifi Handling.
Then we need to merge with the other pull request and check if everything still work as expected. It thin next release should be in 1 or two weeks

**Comment by BradleyFord** [comment] 2023-09-01 10:54
> The fix should already be in the master of the 10th but just around this time we merged my old Repo and have moved around some stuff so please create a new Build out of the master and try again. @BradleyFord I just have flashed today the development_pref branch where you don't need anymore to setup the variables before the build. The Dev Branch at it is has a small Issue to with the wifi Handling. Then we need to merge with the other pull request and check if everything still work as expected. It thin next release should be in 1 or two weeks

Ok thanks so much for the update, I'm not in a super hurry so can wait until then.
At that point can you mark it as a beta release?

**Closed** 2023-11-28 07:46 UTC
Labels: bug, dev
